using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HuntAlerts.Helpers;
public class HuntTrainMessage
{
    //(string Message, string huntKind, string huntWorld, string currentworldName, string currentregionName, string huntregionName, string Posted_Time,string startLocation, string startZone,string locationCoords,bool openmaponArrival ,bool teleporterEnabled,bool lifestreamEnabled)
    public string Message;
    public string huntType;
    public string huntKind;
    public string huntWorld;
    public string currentworldName;
    public string currentregionName;
    public string huntregionName;
    public string Posted_Time;
    public string startLocation;
    public string startZone;
    public string locationCoords;
    public bool openmaponArrival;
    public bool teleporterEnabled;
    public bool lifestreamEnabled;

    public HuntTrainMessage(string message, string huntType, string huntKind, string huntWorld, string currentworldName, string currentregionName, string huntregionName, string posted_Time, string startLocation, string startZone, string locationCoords, bool openmaponArrival, bool teleporterEnabled, bool lifestreamEnabled) //autogenerated
    {
        this.Message = message;
        this.huntType = huntType;
        this.huntKind = huntKind;
        this.huntWorld = huntWorld;
        this.currentworldName = currentworldName;
        this.currentregionName = currentregionName;
        this.huntregionName = huntregionName;
        this.Posted_Time = posted_Time;
        this.startLocation = startLocation;
        this.startZone = startZone;
        this.locationCoords = locationCoords;
        this.openmaponArrival = openmaponArrival;
        this.teleporterEnabled = teleporterEnabled;
        this.lifestreamEnabled = lifestreamEnabled;
    }
}
